export enum IconType {
   home,
   github,
   linkedin,
   download,
   arrowDown,
   bug,
   history,
   projects,
   external,
   mail,
   sheet,
   details,
   security,

   AGILE = "AGILE",
   API_REST = "API_REST",
   BITBUCKET = "BITBUCKET",
   CSS = "CSS",
   DOCKER = "DOCKER",
   FIGMA = "FIGMA",
   GIT = "GIT",
   GITHUB = "GITHUB",
   HTML = "HTML",
   HTML5 = "HTML5",
   ILLUSTRATOR = "ILLUSTRATOR",
   JAVA = "JAVA",
   JAVASCRIPT = "JAVASCRIPT",
   JIRA = "JIRA",
   MICROSERVICES = "MICROSERVICES",
   MONGODB = "MONGODB",
   MVC = "MVC",
   MYSQL = "MYSQL",
   PHOTOSHOP = "PHOTOSHOP",
   PHP = "PHP",
   POSTGRESQL = "POSTGRESQL",
   REACT = "REACT",
   REDUX = "REDUX",
   RESPONSIVE = "RESPONSIVE",
   SASS = "SASS",
   SPRING_BOOT = "SPRING_BOOT",
   SVELTE = "SVELTE",
   TYPESCRIPT = "TYPESCRIPT",
   VS_CODE = "VS_CODE",
   ZUSTAND = "ZUSTAND"
}